// @ts-check
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/coverage/**",
      // Generated by `prisma generate`; not ours to lint.
      "apps/api/src/generated/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
    },
    rules: {
      // Allow deliberately unused parameters when they document a signature
      // (Express error handlers need four arguments to be recognised as such).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "smart"],
    },
  },

  // Node-side code
  {
    files: ["apps/api/**/*.ts", "packages/shared/**/*.ts", "*.js", "*.ts"],
    languageOptions: { globals: globals.node },
  },

  // The seed script and Vitest global setup are CLI entry points; they report
  // progress on stdout by design.
  {
    files: ["apps/api/prisma/seed.ts", "apps/api/test/**/*.ts", "apps/api/src/config/env.ts"],
    rules: { "no-console": "off" },
  },

  // Browser-side code
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
);
